language: php
php:
  - 7.3
  - 7.4

matrix:
  fast_finish: true

env:
  matrix:
    - PREFER_LOWEST=""
    - PREFER_LOWEST="--prefer-lowest"


before_script:
    - rm -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
#    - composer self-update
    - composer update --prefer-source $PREFER_LOWEST

script:
  - ./bin/phpunit --configuration tests/phpunit.xml
  - ./bin/sabre-cs-fixer fix . --dry-run --diff
